name: Mirror to Bitbucket

on:
  push:
    branches: 
      - '**'
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Mirror to Bitbucket
        env:
          BITBUCKET_USERNAME: ${{ secrets.SHABAB_BITBUCKET_USERNAME }}
          BITBUCKET_APP_PASSWORD: ${{ secrets.SHABAB_BITBUCKET_APP_PASSWORD }}
        run: |
          git remote add bitbucket https://${SHABAB_BITBUCKET_USERNAME}:${SHABAB_BITBUCKET_APP_PASSWORD}@bitbucket.org/comp3888_m10_3_/capstone_project.git
          git push bitbucket --all --force
          git push bitbucket --tags --force